import Image from 'next/image';
import Link from 'next/link';
import { hotels } from '../../database/hotel-db';
import { getHotelsInsecure } from '../../database/hotels';

export const metadata = {
  title: 'Hotels page',
  description: 'Generated by create next app',
};

export default async function HotelsPage() {
  const hotels = await getHotelsInsecure();

  return (
    <div>
      These are my hotels
      {hotels.map((hotel) => {
        return (
          <div
            key={`hotels-${hotel.hotelName}`}
            data-test-id={`hotel-type-${hotel.hotelName}`}
          >
            <Link href={`/hotel/${hotel.hotelName}`}>
              <div>{hotel.firstName}</div>
              <Image
                src={`/images/${hotel.hotelName.toLowerCase()}.png`}
                width={300}
                height={200}
                alt={hotel.firstName}
              />
            </Link>
          </div>
        );
      })}
    </div>
  );
}
