import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { getUser } from '../database/users';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'bookingwulf | buy the dip',
  description: 'Generated by Wulius',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionTokenCookie = cookies().get('sessionToken');
  const user = sessionTokenCookie && (await getUser(sessionTokenCookie.value));

  return (
    <html lang="en">
      <body className="bg-[#E8E8E8]">
        <Header username={user?.username} />

        {children}
        <Footer />
      </body>
    </html>
  );
}
